### ISSUE TITLE
add requirements.txt file

### ISSUE THREAD

**Issue by 1578361** [feanor-on-fire/face_recognition#1]
Необходимо прописать файл requirements.txt с использующимися в проекте библиотеками, чтобы при скачивании проекта, можно было установить все зависимости командой `pip install -r requirements.txt`

[Пример requirements.txt](https://github.com/0Kit/antirobot_aiogram/blob/master/requirements.txt)

**Comment by osolovyoff** [comment]
Absolutely agree, is the best practice
