### ISSUE TITLE
add docker container

### ISSUE THREAD

**Issue by 1578361** [feanor-on-fire/face_recognition#3]
Думаю тайтл говорит сам за себя. Необходимо обернуть в докер, чтобы было удобно работать над проектом

**Comment by osolovyoff** [comment]
I don't know exactly for what. Do you want to use docker for processing all events inside to it? For having a unity of all os and architectures?

**Comment by 1578361** [comment]
> I don't know exactly for what. Do you want to use docker for processing all events inside to it? For having a unity of all os and architectures?

Ну да, я сейчас подумал и что-то слабо представляется то, как будет выглядит данное приложение в докере. Просто потом придется писать документацию 😒
